/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sorter;

import java.awt.*;
import java.util.*;
import javax.swing.JButton;

import javax.swing.JFrame;
import javax.swing.JPanel;
import javax.swing.SwingUtilities;
import javax.swing.SwingWorker;
/**
 *
 * @author tremor
 */
public class mainpanel2 extends javax.swing.JPanel {
        private static final long serialVersionUID = 1L;
	private final int WIDTH = 1000, HEIGHT = WIDTH * 9 / 16;
	private final int SIZE = 200;
	private final float BAR_WIDTH = (float)WIDTH / SIZE;
	private float[] bar_height = new float[SIZE];
	private SwingWorker<Void, Void> shuffler, sorter;
	private int current_index, traversing_index;
        private static JButton btnGenerate;

    @Override
    public Dimension preferredSize() {
        return super.preferredSize(); //To change body of generated methods, choose Tools | Templates.
    }

    /**
     * Creates new form mainpanel2
     */
    private mainpanel2() {
        initComponents();
        setBackground(Color.BLACK);
	setPreferredSize(new Dimension(WIDTH, HEIGHT));
    }
    public void paint(Graphics g) {
		g.drawString("Hello",40,40);
		setBackground(Color.WHITE);
		g.fillRect(130, 30,100, 80);
		g.drawOval(30,130,50, 60);
		setForeground(Color.RED);
		g.fillOval(130,130,50, 60);
		g.drawArc(30, 200, 40,50,90,60);
		g.fillArc(30, 130, 40,50,180,40);
		
	}
    
   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 951, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 543, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    public static void main(String[] args){
        //SwingUtilities.invokeLater(() -> {
			JFrame frame = new JFrame("Insertion Sort Visualizer");
			frame.setResizable(false);
			frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
			frame.setContentPane(new mainpanel2());
			frame.validate();
			frame.pack();
			frame.setLocationRelativeTo(null);
			frame.setVisible(true);
                        btnGenerate = new JButton("Generate");
		//});
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
